### ISSUE TITLE
[Feature request] Settings to disable individual parts only + releases on github?

### ISSUE THREAD

**Issue by Apacelus** [elliotwaite/cleantube#1]
Hey, would be nice if you could add the ability to disable parts of this extension (i.e. only enable hiding the channel watermark) via some kinda options window.

**Comment by elliotwaite** [comment]
Thanks for the recommendation. I’ll add this feature soon.

**Comment by elliotwaite** [comment]
I just submitted the updated version for review for both Chrome and Firefox. The Firefox one has already been approved and released, but the Chrome one may take a day or so to be approved. I'll post another comment here when the Chrome update has been released.

Once you have access to the updated version you can try it out and let me know what you think.

**Comment by Apacelus** [comment]
I just updated the firefox extension and it works as expected. Thank you

**Comment by elliotwaite** [comment]
Great! I'll close this issue then.

Thanks again for taking the time to suggest this feature.
