### ISSUE TITLE
v7.4:  No Next/Prev buttons playing playlists (like WatchLater or personal playlists)

### ISSUE THREAD

**Issue by SirVesa** [elliotwaite/cleantube#2]
Playing from Subscriptions or Home tabs, I can use both Seek and Next, but when playing from a playlist I'm only able to use Seek.  The Next/Last buttons don't show.  Also, still have to force close the app, but it's NBD.

**Comment by elliotwaite** [comment]
I think you might have the wrong repo. The CleanTube extension is v0.5, not v7.4, and your issues don't seem related to the CleanTube extension.

**Comment by elliotwaite** [comment]
I'm going to close this issue since it seems unrelated to this extension, but feel free to leave a comment or open a new issue if my assumption is incorrect.
